#Cooldown for daily boss, in milliseconds.
#Default: 1 day = 86400000
#Minimum: 10 seconds = 10000
#Maximum: 7 days = 86400000 * 7 = 604800000
#Range: 10000 ~ 604800000
coolDown = 86400000
#Force spawning any boss without killing it first.
#This mode is only for mod reviewers that need to review some bosses.
#Remember adding the boss id to datapack or else it will crash when you killed the boss.
#Example: minecraft:wither
forceSpawn = ""
#Force unlock all available bosses.
#This will break your gameplay.
forceUnlock = false

